### ISSUE TITLE
On GingerBread, ListView's background looks wried with material theme when one of its item is pressed.

### ISSUE THREAD

**Issue by fengdai** [fengdai/AlertDialogPro#17]
On GingerBread emulator. Choose Material theme(or Material light theme), and show "List Dialog"(or any other dialog contains ListView) . Then press an item and all the other items look like being pressed.

![17](https://cloud.githubusercontent.com/assets/3105406/5234070/dd3562f4-77ec-11e4-9c2d-5c517d4c1d8a.png)

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
Same issue here.

**Comment by fengdai** [comment]
@RaymondBakkerMoonlightMultimedia I think this is caused by an issue of old platform's ListView(Not very sure). Here is a workaround: 3ab68ad1670a7076cc394aab9c917d862e0c303b

**Comment by AndroidDeveloperLB** [comment]
what exactly have you changed?

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
@AndroidDeveloperLB Seems old Android verions behave differently when using @color or @drawable resources. I have yet to test to verify that it has been fixed.

**Comment by AndroidDeveloperLB** [comment]
Ohhh... I remember I read about it somewhere. in order to use a color, you have to use a drawable that has it inside a "shape" xml tag.

**Comment by RaymondBakkerMoonlightMultimedia** [comment]
Just tested it, can confirm that it has been fixed!

**Comment by marbat87** [comment]
Could you please publish the new version on Maven? Thanks in advance

**Comment by fengdai** [comment]
@marbat87 0.2.1 is available now.
