### ISSUE TITLE
Compatibility with support v20

### ISSUE THREAD

**Issue by cbeyls** [fengdai/AlertDialogPro#40]
Hello and thanks for your great work.

I wanted to integrate your library for Holo styled dialogs in an existing project using AppCompat version 20 (pre-material). I don't want to migrate this project to AppCompat v21 because of the visual changes it implies: drawable tinting, new default colors, deprecated features in the ActionBar, ...

However I couldn't integrate AlertDialogPro-theme-holo at all because the core relies on Theme.AppCompat.Dialog. Could you adapt the library to make it inherit from the native themes directly and remove this dependency in order to make it compatible with v20 as well, or do you target v21 and Material Design only from now on?

**Comment by fengdai** [comment]
Hi @cbeyls . For now, I only target v21. If you want to use v20, you can modify the code yourself. It's very easy.

**Comment by fengdai** [comment]
BTW. I think making the core inherit from the native themes directly is not a good idea. Use Theme.AppCompat.Dialog (Whatever v20 or 21) can give dialog a coincident appearance on different platform versions.

**Comment by cbeyls** [comment]
Yes, I was actually suggesting to copy all the Dialog-related styles of AppCompat to your library, in order to have a consistent appearance while also being compatible with v20. But after looking at the source of these styles in detail I realized that there is a lot to copy and the styling is really optimized for Material, so it's a good thing that your library reuses that and I understand the requirement. I'll try to migrate my project to AppCompat v21 soon.

Thank you for your reply and for your work.
