### ISSUE TITLE
Suggestion: publish on those websites

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [fengdai/AlertDialogPro#41]
http://android-libs.com/?page=7
https://github.com/JStumpp/awesome-android

**Comment by fengdai** [comment]
http://android-libs.com/lib/alertdialogpro

**Comment by AndroidDeveloperLB** [comment]
Odd. I didn't find it before

**Comment by AndroidDeveloperLB** [comment]
oh ok, the date is today... :)
