### ISSUE TITLE
adpButtonBarPositiveButtonStyle with Holo theme

### ISSUE THREAD

**Issue by vyndor** [fengdai/AlertDialogPro#45]
Hi,
I'm trying to change text color for positive button. It works well with Material theme but doesn't affect Holo theme.
My styles.xml:
```

    <!-- Application theme. -->
    <style name="AppTheme" parent="AppBaseTheme">
        ...
        <item name="alertDialogProTheme">@style/CustomAlertDialog</item>
    </style>

    <style name="CustomAlertDialog" parent="Theme.AlertDialogPro.Material.Light">
        <item name="adpButtonBarPositiveButtonStyle">@style/CustomDialogPositiveButton</item>
    </style>

    <style name="CustomDialogPositiveButton" parent="Widget.AlertDialogPro.Material.Light.Button">
        <item name="android:textColor">@color/bittersweet</item>
    </style>
```

**Comment by fengdai** [comment]
Sorry, I didn't understand your point. Did you mean your styles didn't work on pre-lollipop device?

**Comment by vyndor** [comment]
No, I would like to customize exactly Holo theme. But style I pass to adpButtonBarPositiveButtonStyle doesn't change anything. Maybe adpButtonBarPositiveButtonStyle  is not supported for Holo?

**Comment by fengdai** [comment]
I have found the reason. I didn't use ```adpButtonBarPositiveButtonStyle``` in the Holo layout.

**Comment by vyndor** [comment]
Thank you!
I'm new to gradle build system, can you please tell me how can I get your latest changes?

**Comment by fengdai** [comment]
You can use 'com.github.fengdai:alertdialogpro-theme-holo:0.2.2'
