### ISSUE TITLE
Add support for the new Support library 22.1

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [fengdai/AlertDialogPro#46]
Now the support library has support for AlertDialogs :

http://android-developers.blogspot.co.il/2015/04/android-support-library-221.html

However, it does miss some stuff, like the ProgressDialog and maybe some themes too.
Please check it out.

**Comment by fengdai** [comment]
If someone uses SupportV7 22.1 or higher, he doesn't need AlertDialogPro anymore... The functionality of SupportV7's AlertDialog is almost the same as AlertDialogPro's. The biggest difference between them is that SupportV7's AlertDialog is official. Well, It's better to choose an official library... I highly suggest you guys to use/migrate to SupportV7's AlertDialog!

**Comment by AndroidDeveloperLB** [comment]
Can you please show some samples of how to use it?

**Comment by fengdai** [comment]
@AndroidDeveloperLB The supportV7 AlertDialog's Java Api is as same as the platform AlertDialog's (and AlertDialogPro's). Just change ```android.app.AlertDialog``` to ```android.support.v7.app.AlertDialog```.

**Comment by AndroidDeveloperLB** [comment]
And it provides all that this library provides?

**Comment by fengdai** [comment]
It provides the same Java APIs and similar attributes for building and theming Dialog. So I think it provides all that this library provides.

PS. I haven't used it. I'll use it in my next project.

**Comment by AndroidDeveloperLB** [comment]
Can you please let us know how well it worked for you?
