### ISSUE TITLE
Error when tryin do compile 23 SDK version 

### ISSUE THREAD

**Issue by viliamvolosv** [fengdai/AlertDialogPro#53]
<item name="android:textColorLink">@color/link_text_material_light</item>

Error:(88, 45) No resource found that matches the given name (at 'android:textColorLink' with value '@color/link_text_material_light').

i have a error in alertdialogpro-theme-materia when compile  using 23 SDK version

**Comment by burnaz** [comment]
Same problem here

**Comment by richardradics** [comment]
same problem here

**Comment by fengdai** [comment]
0.2.4 is available now.
