### ISSUE TITLE
hope upgrade to compile 'com.android.support:appcompat-v7:23.1.1'

### ISSUE THREAD

**Issue by LiuDeng** [fengdai/AlertDialogPro#57]
import android.support.v7.internal.widget.TintManager;
import android.support.v7.internal.widget.TintTypedArray;
have error with 23.1.1 hope upgrade to compile 'com.android.support:appcompat-v7:23.1.1'

**Comment by LiuDeng** [comment]
http://stackoverflow.com/questions/33724592/package-android-support-v7-internal-view-menu-does-not-exist-cannot-find-symbol

**Comment by fengdai** [comment]
0.2.6 is available now.
