### ISSUE TITLE
Failed to resolve: com.github.fengdai:alertdialogpro-theme-material:0.2.6

### ISSUE THREAD

**Issue by LiuDeng** [fengdai/AlertDialogPro#59]
Failed to resolve: com.github.fengdai:alertdialogpro-theme-material:0.2.6

**Comment by fengdai** [comment]
Clean and rebuild?

**Comment by LiuDeng** [comment]
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.fengdai%22%20AND%20a%3A%22alertdialogpro-theme-material%22
