### ISSUE TITLE
have error with compile 'com.android.support:appcompat-v7:23.2.1'

### ISSUE THREAD

**Issue by LiuDeng** [fengdai/AlertDialogPro#64]
import android.support.v7.internal.widget.TintManager;
import android.support.v7.internal.widget.TintTypedArray;
have error with 23.2.1 hope upgrade to compile 'com.android.support:appcompat-v7:23.2.1'

**Comment by LiuDeng** [comment]
亲 坐等新版本~

**Comment by fengdai** [comment]
暂时不出新版本，先用SNAPSHOT:
compile 'com.github.fengdai:alertdialogpro-theme-material:0.2.7-SNAPSHOT'
