### ISSUE TITLE
示例代码报错？

### ISSUE THREAD

**Issue by HyperSimon** [fengdai/AlertDialogPro#67]
this is my code 
`package com.roselism.listdialog_alpha;

import com.alertdialogpro.AlertDialogPro;

import android.content.DialogInterface;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.Button;

public class MainActivity extends AppCompatActivity {

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    AlertDialogPro.Builder builder = new AlertDialogPro.Builder(this);
    builder.setIcon(R.drawable.adp_item_background_material_dark).
            setTitle("Title").
            setMessage("Message Body").
            setNeutralButton("Neutral", null).
            setPositiveButton("Positive", null).
            setNegativeButton("Negative", null).
            show();
}
```

}
`
and this is what i get, What shoud i do ?
`
    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
`

**Comment by fengdai** [comment]
As you have already used supportV7, I suggest you use '''android.support.v7.app.AlertDialog''' instead.
